baseurl = "/"
title = "tawon's dev blog"
languageCode = "en-us"
theme = "mainroad"
cleanDestinationDir = true

[Site.Params.Author] # Used in authorbox
  name = "Taewon Park"
  # bio = "John Doe's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
  bio = "tw bio"
  avatar = "img/avatar.png"

[Params.style.vars]
  highlightColor = "#e12d00" # Override highlight color

  # Override font-family sets
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  # Secondary font-family set responsible for pre, code, kbd, and samp tags font
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"


[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social"]

# [Params]
#   description = "John Doe's Personal blog about everything" # Site description. Used in meta description
#   copyright = "John Doe" # Footer copyright holder, otherwise will use site title
#   opengraph = true # Enable OpenGraph if true
#   schema = true # Enable Schema
#   twitter_cards = true # Enable Twitter Cards if true
#   readmore = false # Show "Read more" button in list if true
#   authorbox = true # Show authorbox at bottom of pages if true
#   toc = true # Enable Table of Contents
#   pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
#   post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
#   mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
#   dateformat = "2006-01-02" # Change the format of dates
#   mathjax = true # Enable MathJax
#   mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
#   mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
#   googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
#   customCSS = ["css/custom.css"] # Include custom CSS files
#   customJS = ["js/custom.js"] # Include custom JS files

# [Params.logo]
#   image = "img/placeholder.png" # Logo image. Path relative to "static"
#   title = "GuBoC's Blog123" # Logo title, otherwise will use site title
#   subtitle = "Just another site" # Logo subtitle

# [Params.thumbnail]
#   visibility = ["list", "post"] # Control thumbnail visibility


[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = false # Enable counter for each category in "Categories" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  cached = false # activate cache if true
  # Enable parts of social widget
  # facebook = "username"
  # twitter = "username"
  # instagram = "username"
  github = "guboc11"
  linkedin = "tw-park317"
  telegram = "Tommy_df"
  # gitlab = "username"
  # bitbucket = "username"
  email = "guboc11@gmail.com"

# Custom social links
[[Params.widgets.social.custom]]
  title = "ðŸ’¼ Portfolio"
  url = "https://ysblockblock.notion.site/28f2efc9d62580b6bb63d30360f1c6e1"
  # icon = "youtube.svg" # Optional. Path relative to "layouts/partials"
  # rel = "noopener noreferrer" # Set to false to remove the rel attribute
